language: php
sudo: false
dist: trusty
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    - anthonys@hexonet.net
    - tseelamkurthi@hexonet.net
    on_success: never
    on_failure: always
php:
- 5.6.38
- 7.0.32
- 7.1.26
- 7.2.15
- 7.3.2
cache:
  directories:
  - "~/.npm"
  - node_modules
install:
- sudo apt-get install pandoc
- composer install --dev
script:
- composer run-script codeCheck
#- composer run-script test
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
  git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  && git fetch --tags
  && nvm install lts/* 
  && nvm use lts/*
  && npm prune && npm i
  && composer install --no-dev
  && npx travis-deploy-once "npx semantic-release" ; fi
